"""rayen

Revision ID: 0521a30e9a09
Revises: da37594160fc
Create Date: 2025-10-29 13:40:00.203451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0521a30e9a09'
down_revision: Union[str, None] = 'da37594160fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_cols', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_cols')
    # ### end Alembic commands ###
