"""your_message

Revision ID: 26b0d86ee351
Revises: 0521a30e9a09
Create Date: 2025-11-20 16:48:34.241492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b0d86ee351'
down_revision: Union[str, None] = '0521a30e9a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_768_13_vector_idx', table_name='collection_768_13', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_768_13')
    op.drop_index('collection_768_12_vector_idx', table_name='collection_768_12', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_768_12')
    op.drop_column('projects', 'new_cols')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_cols', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('collection_768_12',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_768_12_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_768_12_pkey')
    )
    op.create_index('collection_768_12_vector_idx', 'collection_768_12', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('collection_768_13',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_768_13_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_768_13_pkey')
    )
    op.create_index('collection_768_13_vector_idx', 'collection_768_13', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
