"""add assets relationship to project

Revision ID: 59cfe9cbb3a2
Revises: 6f465e8768a9
Create Date: 2025-10-28 18:34:31.748289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cfe9cbb3a2'
down_revision: Union[str, None] = '6f465e8768a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
