"""adding new col 

Revision ID: 68eded7c2690
Revises: 849fcd565a06
Create Date: 2025-10-26 14:42:23.455559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eded7c2690'
down_revision: Union[str, None] = '849fcd565a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_dummy_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_dummy_col')
    # ### end Alembic commands ###
