"""current status

Revision ID: 6f465e8768a9
Revises: 68eded7c2690
Create Date: 2025-10-27 19:18:00.385939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f465e8768a9'
down_revision: Union[str, None] = '68eded7c2690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_dummy_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_dummy_col', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
